spring.application.name=telegram-service
spring.main.allow-bean-definition-overriding=true

gemini.uri = https://generativelanguage.googleapis.com/v1beta/interactions
gemini.apikey=${GEMINI_API_KEY}
gemini.model=gemini-3.1-flash-lite


groq.uri=https://api.groq.com/openai/v1/responses
groq.apikey=${GROQ_API_KEY}
groq.model=openai/gpt-oss-20b

telegram.token=${TELEGRAM_TOKEN}
telegram.username=van_ai_v1_bot